### PR TITLE
Issue templates for the Pulumi organization

### PR DESCRIPTION
**Pull request by infin8x**
As part of some ongoing process changes, I'm proposing a standard set of issue templates to automatically apply to all of our repositories.

### CODE REVIEW

**Review by leezen — APPROVED** [review]

**Comment by leezen** [comment]
Generally seems fine, but is there a way to disable this for our private repos?

**Comment by infin8x** [comment]
There isn't - curious why you want to do so?

**Comment by leezen** [comment]
Main to save ourselves the annoyance where we know we want to open a different type of issue not covered by the templates and having to 'zero out' the template. Not a huge deal, but probably something that needs to be explained to folks within the org who might think the lack of blank issue template suggests they must conform to an existing template.

**Comment by infin8x** [comment]
Gotcha. I'll take that out for now, may as well leave the flexibility. We can revisit if it becomes a big triage challenge in the public-facing repos.

**Pull request merged**
